### ISSUE TITLE
Is it possible to retrieve a single entry?

### ISSUE THREAD

**Issue by ismay** [contentful-labs/contentful-metalsmith#16]
I've tried specifying an `entry_id` in my frontmatter, to retrieve a single entry, but that doesn't seem to work ([source here](https://github.com/DefactoSoftware/capp-static/blob/master/src/index.html)):

```
---
contentful:
  space_id: spaceidhere
  entry_id: entryidhere
---
page content
```

I'm still getting an array of entries. Am I doing something wrong, or is this currently not possible?

---

By the way, looping through the entries and displaying the contents works fine. It's just that I'd like to be able to link a certain page to an entry_id.

**Comment by grncdr** [comment]
For this you might try `sys.id: entryidhere`, which would be the syntax for filtering the API query down to a   specific entry.

**Comment by ismay** [comment]
So how would I use that in the frontmatter? This:

```javascript
---
contentful:
  space_id: 5uuu5mgc96pk
  sys.id: 23BKf9sfvaMcY8A4S2Cckc
---
```

Doesn't make any difference in the returned object (still returns an array of entries). And this:

```
---
contentful:
  space_id: 5uuu5mgc96pk
    sys.id: 23BKf9sfvaMcY8A4S2Cckc
---
```
Returns `undefined`.

**Comment by ismay** [comment]
Or do you mean filtering the returned results myself? Because that seems rather inefficient when the api accepts an `entry_id` as parameter. Or has that not been implemented in contentful-metalsmith?

**Comment by grncdr** [comment]
I think this one was almost right:

```yaml
---
contentful:
  space_id: 5uuu5mgc96pk
    filter:
      sys.id: 23BKf9sfvaMcY8A4S2Cckc
---
```
but `filter` shouldn't be indented under `space_id`:

```yaml
---
contentful:
  space_id: 5uuu5mgc96pk
  filter:
    sys.id: 23BKf9sfvaMcY8A4S2Cckc
---
```
