### ISSUE TITLE
Getting structure right

### ISSUE THREAD

**Issue by adamliptrot** [contentful-labs/contentful-metalsmith#17]
I'm adding this into a Metalsmith build and am having problems getting the structure to work.
I have this in src/news/index.md:
```
---
title: News
contentful:
    space_id: <space_id_here>
    entry_template: newspost.hbt
    entry_filename_pattern: :sys.locale/:fields.slug
    permalink_style: true
template: news.hbt
---
```
which produces the content in both the list view and individual entries but doesn't structure the folders correctly (it places id-named folders in the root with index.html in each)

If I indent the metadata as per the example:
```
---
title: News
contentful:
    space_id: <space_id_here>
        entry_template: newspost.hbt
        entry_filename_pattern: :sys.locale/:fields.slug
        permalink_style: true
template: news.hbt
---
```
then nothing is processed - no list or entry views are generated.
Can you point me in the right direction?
